import { Bounty, PosterProfile } from "./types";

export const MOCK_USERS: Record<string, PosterProfile> = {
  alex: {
    id: "user-1",
    name: "Alex Rivera",
    username: "alex_eco",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 98,
    completedCleanups: 34,
    reportedCount: 18,
  },
  sam: {
    id: "user-2",
    name: "Samantha Santos",
    username: "sam_baywalk",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 95,
    completedCleanups: 52,
    reportedCount: 12,
  },
  maria: {
    id: "user-3",
    name: "Maria Clara Reyes",
    username: "maria_cleanup",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 100,
    completedCleanups: 89,
    reportedCount: 45,
  },
  jordan: {
    id: "user-4",
    name: "Jordan Bautista",
    username: "jordan_patrol",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 92,
    completedCleanups: 15,
    reportedCount: 7,
  },
};

export const INITIAL_BOUNTIES: Bounty[] = [
  {
    id: "bounty-1",
    title: "Manila Baywalk Seawall Plastic Waste & Bottles",
    description: "Single-use plastic bottles, discarded food packaging, and beverage sachets accumulated along the Roxas Boulevard baywalk rocks.",
    // Plastic bags, bottles and single-use packaging washed onto a tropical beach waterline — Manila Bay
    beforeImageUrl: "https://images.unsplash.com/photo-1769305550506-9a9b6265e92c?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 250,
    karmaReward: 50,
    wasteCategory: "plastic",
    severity: "high",
    location: {
      lat: 14.5746,
      lng: 120.9818,
      address: "Roxas Blvd Promenade near Dolomite Beach",
      neighborhood: "Malate",
      city: "Manila, Philippines",
    },
    distanceMiles: 0.6,
    postedBy: MOCK_USERS.sam,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    timeAgo: "25m ago",
    expiresAt: new Date(Date.now() + 48 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "25m ago",
        event: "Bounty reported with verified live camera & GPS in Manila Bay",
        actor: "Samantha Santos (@sam_baywalk)",
      },
      {
        timestamp: "24m ago",
        event: "Automated anti-fraud checks & cooldown radius passed",
        actor: "TrashMap Manila System",
      },
    ],
  },
  {
    id: "bounty-2",
    title: "Paco Railway Perimeter Illegally Dumped Tires",
    description: "Stack of discarded rubber motorcycle & car tires blocking drainage near the railway intersection.",
    // Stacked worn rubber tires illegally dumped roadside — exact match for bulky tire waste near PNR
    beforeImageUrl: "https://images.unsplash.com/photo-1748103473104-5382baf20c74?w=800&auto=format&fit=crop&q=82",
    status: "in_progress",
    points: 400,
    karmaReward: 80,
    wasteCategory: "bulky",
    severity: "high",
    location: {
      lat: 14.5790,
      lng: 120.9950,
      address: "Pedro Gil St & Paco PNR Perimeter",
      neighborhood: "Paco",
      city: "Manila, Philippines",
    },
    distanceMiles: 1.1,
    postedBy: MOCK_USERS.jordan,
    claimedBy: MOCK_USERS.maria,
    createdAt: new Date(Date.now() - 65 * 60000).toISOString(),
    timeAgo: "1h ago",
    expiresAt: new Date(Date.now() + 24 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "1h ago",
        event: "Bounty reported with photo evidence",
        actor: "Jordan Bautista (@jordan_patrol)",
      },
      {
        timestamp: "15m ago",
        event: "Bounty accepted & cleanup underway",
        actor: "Maria Clara Reyes (@maria_cleanup)",
      },
    ],
  },
  {
    id: "bounty-3",
    title: "Pasig River Esplanade Crushed Cans & Debris",
    description: "Crushed aluminum drink cans, energy drink tins, and plastic cups left near the promenade view deck by Jones Bridge.",
    // Crushed aluminum drink cans and metal bottle debris on concrete — riverside promenade littering
    beforeImageUrl: "https://images.unsplash.com/photo-1746008148815-447e8a1b6a69?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 200,
    karmaReward: 40,
    wasteCategory: "cans",
    severity: "medium",
    location: {
      lat: 14.5960,
      lng: 120.9774,
      address: "Muelle del Banco Nacional, Jones Bridge",
      neighborhood: "Binondo",
      city: "Manila, Philippines",
    },
    distanceMiles: 0.8,
    postedBy: MOCK_USERS.alex,
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    timeAgo: "40m ago",
    expiresAt: new Date(Date.now() + 36 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "40m ago",
        event: "Bounty reported",
        actor: "Alex Rivera (@alex_eco)",
      },
    ],
  },
  {
    id: "bounty-4",
    title: "Binondo Ongpin St Overflowing Trash & Boxes",
    description: "Overflowing commercial garbage receptacle with damp cardboard packaging, food containers, and discarded paper boxes.",
    // Overflowing urban garbage bins with cardboard, food containers, and mixed refuse — Chinatown alley
    beforeImageUrl: "https://images.unsplash.com/photo-1639844994641-e6513483de5e?w=800&auto=format&fit=crop&q=82",
    // Clean empty sidewalk and alley after successful cleanup — verified "after" state
    afterImageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80",
    status: "pending_verification",
    points: 180,
    karmaReward: 35,
    wasteCategory: "mixed",
    severity: "low",
    location: {
      lat: 14.6001,
      lng: 120.9760,
      address: "Ongpin St corner Tomas Pinpin",
      neighborhood: "Chinatown / Binondo",
      city: "Manila, Philippines",
    },
    distanceMiles: 1.4,
    postedBy: MOCK_USERS.sam,
    claimedBy: MOCK_USERS.alex,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    timeAgo: "2h ago",
    expiresAt: new Date(Date.now() + 12 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "2h ago",
        event: "Bounty reported",
        actor: "Samantha Santos (@sam_baywalk)",
      },
      {
        timestamp: "45m ago",
        event: "Bounty claimed",
        actor: "Alex Rivera (@alex_eco)",
      },
      {
        timestamp: "10m ago",
        event: "Proof 'After' photo submitted — awaiting official review",
        actor: "Alex Rivera (@alex_eco)",
      },
    ],
  },
  {
    id: "bounty-5",
    title: "🔥 Baseco Port Area Coastal Clean-Up Mega Bounty",
    description: "Official Manila City community coastal cleanup pool! Massive collection of washed-up marine debris, plastic nets, and driftwood.",
    // Polluted tropical coastline with accumulated marine debris, plastic nets and ocean litter — Baseco beachfront
    beforeImageUrl: "https://images.unsplash.com/photo-1768056044705-68335bad33e6?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 600,
    karmaReward: 120,
    wasteCategory: "mixed",
    severity: "critical",
    location: {
      lat: 14.5925,
      lng: 120.9575,
      address: "Baseco Compound Beachfront",
      neighborhood: "Port Area",
      city: "Manila, Philippines",
    },
    distanceMiles: 1.8,
    postedBy: MOCK_USERS.maria,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    timeAgo: "3h ago",
    expiresAt: new Date(Date.now() + 72 * 3600000).toISOString(),
    eventId: "event-manila-bay-2026",
    eventTitle: "Manila Bay Environmental Task Force Drive",
    isHighReward: true,
    timeline: [
      {
        timestamp: "3h ago",
        event: "Official Metro Manila LGU Event bounty published",
        actor: "Maria Clara Reyes (Manila Parks & Cleanliness)",
      },
    ],
  },
  {
    id: "bounty-6",
    title: "Intramuros Baluarte Broken Beer Bottles & Glass",
    description: "Shattered glass bottles and aluminum crown caps scattered near the historic stone fortress walkway.",
    // Shattered glass bottles and broken bottle fragments scattered on pavement — Intramuros stone walkway
    beforeImageUrl: "https://images.unsplash.com/photo-1683694705248-220d316db74e?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 220,
    karmaReward: 45,
    wasteCategory: "glass",
    severity: "medium",
    location: {
      lat: 14.5888,
      lng: 120.9740,
      address: "General Luna St near Baluarte de San Diego",
      neighborhood: "Intramuros",
      city: "Manila, Philippines",
    },
    distanceMiles: 0.5,
    postedBy: MOCK_USERS.jordan,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    timeAgo: "1.5h ago",
    expiresAt: new Date(Date.now() + 40 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "1.5h ago",
        event: "Bounty reported with geo-tag",
        actor: "Jordan Bautista (@jordan_patrol)",
      },
    ],
  },
  {
    id: "bounty-7",
    title: "Luneta Park Central Lawn Food Containers & Wrappers",
    description: "Scattered plastic cups, Styrofoam meal packs, and snack packaging on the grass near the Rizal Monument reflection pool.",
    // Discarded plastic cups, food wrappers and Styrofoam scattered on park grass — Luneta after weekend crowds
    beforeImageUrl: "https://images.unsplash.com/photo-1592890278983-18616401d4ed?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 200,
    karmaReward: 40,
    wasteCategory: "plastic",
    severity: "medium",
    location: {
      lat: 14.5826,
      lng: 120.9787,
      address: "Rizal Park Central Lawn & TM Kalaw",
      neighborhood: "Ermita",
      city: "Manila, Philippines",
    },
    distanceMiles: 0.3,
    postedBy: MOCK_USERS.alex,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    timeAgo: "15m ago",
    expiresAt: new Date(Date.now() + 48 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "15m ago",
        event: "Bounty reported during morning walk",
        actor: "Alex Rivera (@alex_eco)",
      },
    ],
  },
  {
    id: "bounty-8",
    title: "Quiapo Plaza Miranda Styrofoam & Street Litter",
    description: "Discarded take-away containers, single-use cups, and plastic wrappers accumulated outside the market alley.",
    // Piled Styrofoam cups and plastic packaging lining an urban sidewalk outside a busy street market
    beforeImageUrl: "https://images.unsplash.com/photo-1743796360878-0a4c3ef47925?w=800&auto=format&fit=crop&q=82",
    status: "open",
    points: 170,
    karmaReward: 35,
    wasteCategory: "plastic",
    severity: "low",
    location: {
      lat: 14.5990,
      lng: 120.9835,
      address: "Plaza Miranda & Quezon Blvd",
      neighborhood: "Quiapo",
      city: "Manila, Philippines",
    },
    distanceMiles: 1.2,
    postedBy: MOCK_USERS.sam,
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
    timeAgo: "1.8h ago",
    expiresAt: new Date(Date.now() + 30 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "1.8h ago",
        event: "Bounty reported",
        actor: "Samantha Santos (@sam_baywalk)",
      },
    ],
  },
];
