import { Bounty, PosterProfile } from "./types";

export const MOCK_USERS: Record<string, PosterProfile> = {
  alex: {
    id: "user-1",
    name: "Alex Rivera",
    username: "alex_eco",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 98,
    completedCleanups: 34,
    reportedCount: 18,
  },
  sam: {
    id: "user-2",
    name: "Sam Chen",
    username: "green_sam",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 95,
    completedCleanups: 52,
    reportedCount: 12,
  },
  maria: {
    id: "user-3",
    name: "Maria Rodriguez",
    username: "maria_clean",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 100,
    completedCleanups: 89,
    reportedCount: 45,
  },
  jordan: {
    id: "user-4",
    name: "Jordan Taylor",
    username: "jordan_outdoors",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reliabilityScore: 92,
    completedCleanups: 15,
    reportedCount: 7,
  },
};

export const INITIAL_BOUNTIES: Bounty[] = [
  {
    id: "bounty-1",
    title: "Zilker Park Picnic Area Litter",
    description: "Multiple plastic bottles, disposable beverage cups, and scattered food containers near Picnic Shelter C after a weekend gathering.",
    beforeImageUrl: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80",
    status: "open",
    points: 150,
    karmaReward: 30,
    wasteCategory: "plastic",
    severity: "medium",
    location: {
      lat: 30.2669,
      lng: -97.7728,
      address: "2100 Barton Springs Rd, Shelter C",
      neighborhood: "Zilker",
      city: "Austin, TX",
    },
    distanceMiles: 0.4,
    postedBy: MOCK_USERS.alex,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    timeAgo: "25m ago",
    expiresAt: new Date(Date.now() + 48 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "25m ago",
        event: "Bounty reported with verified live camera & GPS",
        actor: "Alex Rivera (@alex_eco)",
      },
      {
        timestamp: "24m ago",
        event: "Automated anti-fraud checks & cooldown radius passed",
        actor: "TrashMap System",
      },
    ],
  },
  {
    id: "bounty-2",
    title: "Greenbelt Trailhead Illegally Dumped Tires",
    description: "Two vehicle tires and discarded auto parts near the Barton Creek Greenbelt trailhead parking area.",
    beforeImageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80",
    status: "in_progress",
    points: 350,
    karmaReward: 60,
    wasteCategory: "bulky",
    severity: "high",
    location: {
      lat: 30.2520,
      lng: -97.7950,
      address: "3755 S Capital of Texas Hwy",
      neighborhood: "Barton Hills",
      city: "Austin, TX",
    },
    distanceMiles: 1.2,
    postedBy: MOCK_USERS.sam,
    claimedBy: MOCK_USERS.maria,
    createdAt: new Date(Date.now() - 65 * 60000).toISOString(),
    timeAgo: "1h ago",
    expiresAt: new Date(Date.now() + 24 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "1h ago",
        event: "Bounty reported",
        actor: "Sam Chen (@green_sam)",
      },
      {
        timestamp: "15m ago",
        event: "Bounty claimed & accepted for cleanup",
        actor: "Maria Rodriguez (@maria_clean)",
      },
    ],
  },
  {
    id: "bounty-3",
    title: "Town Lake Boardwalk Debris & Cans",
    description: "Aluminum cans, broken glass fragments, and packaging materials scattered along the pedestrian walkway near mile marker 4.",
    beforeImageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80",
    status: "open",
    points: 250,
    karmaReward: 45,
    wasteCategory: "cans",
    severity: "medium",
    location: {
      lat: 30.2581,
      lng: -97.7443,
      address: "Ann & Roy Butler Hike-and-Bike Trail",
      neighborhood: "Downtown Austin",
      city: "Austin, TX",
    },
    distanceMiles: 0.8,
    postedBy: MOCK_USERS.jordan,
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    timeAgo: "40m ago",
    expiresAt: new Date(Date.now() + 36 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "40m ago",
        event: "Bounty reported",
        actor: "Jordan Taylor (@jordan_outdoors)",
      },
    ],
  },
  {
    id: "bounty-4",
    title: "Congress Ave Overflowing Trash Bin",
    description: "Windblown takeout containers and disposable cups overflowing around the street corner receptacle.",
    beforeImageUrl: "https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=800&auto=format&fit=crop&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&auto=format&fit=crop&q=80",
    status: "pending_verification",
    points: 100,
    karmaReward: 20,
    wasteCategory: "mixed",
    severity: "low",
    location: {
      lat: 30.2672,
      lng: -97.7431,
      address: "412 Congress Ave & 4th St",
      neighborhood: "Downtown",
      city: "Austin, TX",
    },
    distanceMiles: 1.8,
    postedBy: MOCK_USERS.alex,
    claimedBy: MOCK_USERS.sam,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    timeAgo: "2h ago",
    expiresAt: new Date(Date.now() + 12 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "2h ago",
        event: "Bounty reported",
        actor: "Alex Rivera (@alex_eco)",
      },
      {
        timestamp: "45m ago",
        event: "Bounty claimed",
        actor: "Sam Chen (@green_sam)",
      },
      {
        timestamp: "10m ago",
        event: "Proof 'After' photo submitted — awaiting verification",
        actor: "Sam Chen (@green_sam)",
      },
    ],
  },
  {
    id: "bounty-5",
    title: "🔥 Earth Day Zilker Park Massive Sweep",
    description: "Official community sweep event for the spring festival grounds. Multiple bag bounty with extra event badges!",
    beforeImageUrl: "https://images.unsplash.com/photo-1528190336454-13cd56b45b5a?w=800&auto=format&fit=crop&q=80",
    status: "open",
    points: 500,
    karmaReward: 100,
    wasteCategory: "mixed",
    severity: "high",
    location: {
      lat: 30.2740,
      lng: -97.7510,
      address: "Zilker Great Lawn Central",
      neighborhood: "Zilker",
      city: "Austin, TX",
    },
    distanceMiles: 0.6,
    postedBy: MOCK_USERS.maria,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    timeAgo: "3h ago",
    expiresAt: new Date(Date.now() + 72 * 3600000).toISOString(),
    eventId: "event-earth-day-2026",
    eventTitle: "Annual Austin Green Cleanup Sweep",
    isHighReward: true,
    timeline: [
      {
        timestamp: "3h ago",
        event: "Official Community Event bounty published",
        actor: "Maria Rodriguez (Parks Official)",
      },
    ],
  },
  {
    id: "bounty-6",
    title: "Shoal Creek Trail Discarded Cardboard Boxes",
    description: "Collapsed packaging boxes and Styrofoam packing peanuts dumped near the pedestrian footbridge.",
    beforeImageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80",
    status: "open",
    points: 200,
    karmaReward: 40,
    wasteCategory: "bulky",
    severity: "medium",
    location: {
      lat: 30.2820,
      lng: -97.7480,
      address: "Shoal Creek Trailhead & 24th St",
      neighborhood: "West Campus",
      city: "Austin, TX",
    },
    distanceMiles: 2.1,
    postedBy: MOCK_USERS.jordan,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    timeAgo: "1.5h ago",
    expiresAt: new Date(Date.now() + 40 * 3600000).toISOString(),
    timeline: [
      {
        timestamp: "1.5h ago",
        event: "Bounty reported",
        actor: "Jordan Taylor (@jordan_outdoors)",
      },
    ],
  },
];
